### ISSUE TITLE
Seek backward/forward by 5 seconds is buggy

### ISSUE THREAD

**Issue by nzarbayezid** [killergerbah/asbplayer#139]
I don't know how to explain this, but 90% of the time the 5 sec is not working, normally it seems to work fine but when you are watching a move in killergerbah.github.io/asbplayer/ player it's glitchy, sometimes it Seek backward by 2 min or 45 sec or any random number, that randomize make me feel maybe it is glitching with the subtitles or it is a bug with the pause button, I mean maybe it will Seek backward to the last time you paused the video,

I got it with a screen recorder one time, what I did was paused the video and play it, then waited for some time while the video is played then I pressed A to Seek backward but it jumped from 19:27 to 18:43, as I said the Seek backward time is randomized each time that's why I suspected it to be the pause button

https://user-images.githubusercontent.com/101425664/165648228-7bafcc05-1ab1-4d9a-9460-b1012444f329.mp4

**Comment by nzarbayezid** [comment]
I just downloaded the 10-sec update, I'm not saying the bug is fixed, but I tested it, so far the bug didn't appear, I'll let you know if it appears again tonight

**Comment by nzarbayezid** [comment]
the bug still exists, i was testing it really fast and i wasn't watching the video in full screen, i mean with F11, so i don't know what's causing the problem

**Comment by killergerbah** [comment]
@nzarbayezid Thanks for reporting. It looks like it happens when the subtitle player is hidden and it still receives the keyboard input. Since it's hidden it's internal clock is probably not synced up with the actual video.

**Comment by nzarbayezid** [comment]
hopefully, you know how to fix it?

**Comment by killergerbah** [comment]
@nzarbayezid Thanks again for reporting and sorry for the inconvenience caused. I've deployed a fix - if you're able to please let me know if the problem is still occurring for you.

**Comment by nzarbayezid** [comment]
I watched a whole movie with it there was no problem, so I think it's fixed if it's not gonna appear again, I'm gonna Close with a comment tomorrow if I was certain that the problem is not appearing again, thanks

**Comment by killergerbah** [comment]
@nzarbayezid is it still happening?

**Comment by nzarbayezid** [comment]
thanks, it got fixed, I don't think it's gonna happen again
